### ISSUE TITLE
PyFolio install from PyPI is broken on Python 3 due to outdated wsgiref dependency.

### ISSUE THREAD

**Issue by ssanderson** [quantopian/pyfolio#154]
```
$ mkvirtualenv -p $(which python3) test
$ pip install pyfolio
Collecting pyfolio
  Using cached pyfolio-0.1.tar.gz
Collecting funcsigs>=0.4 (from pyfolio)
  Using cached funcsigs-0.4-py2.py3-none-any.whl
Collecting matplotlib>=1.4.0 (from pyfolio)
  Using cached matplotlib-1.4.3.tar.gz
Collecting mock>=1.1.2 (from pyfolio)
  Using cached mock-1.3.0-py2.py3-none-any.whl
Collecting numpy>=1.9.1 (from pyfolio)
  Using cached numpy-1.9.3.tar.gz
Collecting pandas>=0.15.0 (from pyfolio)
Collecting pyparsing>=2.0.3 (from pyfolio)
  Using cached pyparsing-2.0.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.4.2 (from pyfolio)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Collecting pytz>=2014.10 (from pyfolio)
  Using cached pytz-2015.6-py2.py3-none-any.whl
Collecting scikit-learn>=0.15.0 (from pyfolio)
  Using cached scikit-learn-0.16.1.tar.gz
Collecting scipy>=0.14.0 (from pyfolio)
  Using cached scipy-0.16.0.tar.gz
Collecting seaborn>=0.6.0 (from pyfolio)
  Using cached seaborn-0.6.0.tar.gz
Collecting statsmodels>=0.5.0 (from pyfolio)
  Using cached statsmodels-0.6.1.tar.gz
Collecting wsgiref>=0.1.2 (from pyfolio)
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/user/1000/pip-build-ax77mnu_/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/user/1000/pip-build-ax77mnu_/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'
```

This looks like it's fixed on master, but we haven't yet pushed to PyPI.

cc @twiecki

**Comment by timverheyden** [comment]
Any updates on this? Would love to start working with PyFolio but can't get it installed.

**Comment by twiecki** [comment]
@timverheyden I just uploaded 0.2 to pypi, can you try if it works for you and let me know?

**Comment by timverheyden** [comment]
Works as a charm. Thanks man! Excellent work!!!
