### ISSUE TITLE
test_sector_exposure test breaks in Python 3

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#202]
```
>nosetests --pdb tests/
..[1] > /home/wiecki/working/projects/quant/pyfolio/pyfolio/tests/test_pos.py(118)test_sector_exposure()
-> self.assertEqual(len(w), 0)
   4 frames hidden (try 'help hidden_frames')
(Pdb++) c
F.............................................
======================================================================
FAIL: [with positions=            0  1  2  cash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wiecki/miniconda3/lib/python3.4/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/wiecki/working/projects/quant/pyfolio/pyfolio/tests/test_pos.py", line 118, in test_sector_exposure
    self.assertEqual(len(w), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 48 tests in 2.377s

FAILED (failures=1)
```

@ACampbell22 I think you wrote that test, would you mind taking a look?

**Comment by ACampbell22** [comment]
Tacked the fix onto this PR: https://github.com/quantopian/pyfolio/pull/201
