### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#244]
```
/usr/share/themes/Lubuntu-default/gtk-2.0/apps/thunar.rc:55: error: invalid string constant "thunar-statusbar", expected valid string constant
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    pf.create_returns_tear_sheet(returns)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+61.gfda0433.dirty-py2.7.egg/pyfolio/plotting.py", line 46, in call_w_context
    return func(*args, **kwargs)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+61.gfda0433.dirty-py2.7.egg/pyfolio/tears.py", line 299, in create_returns_tear_sheet
    returns, ax=ax_rolling_risk)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+61.gfda0433.dirty-py2.7.egg/pyfolio/plotting.py", line 149, in plot_rolling_fama_french
    rolling_window=rolling_window)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+61.gfda0433.dirty-py2.7.egg/pyfolio/timeseries.py", line 692, in rolling_fama_french
    start=returns.index[0], end=returns.index[-1])
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+61.gfda0433.dirty-py2.7.egg/pyfolio/utils.py", line 298, in load_portfolio_risk_factors
    five_factors = get_returns_cached(filepath, get_fama_french, end)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+61.gfda0433.dirty-py2.7.egg/pyfolio/utils.py", line 159, in get_returns_cached
    mkdir(cache_dir())
OSError: [Errno 17] File exists: '/home/fbraenns/.cache/pyfolio'
```

Any idea @llllllllll?

**Comment by llllllllll** [comment]
https://github.com/quantopian/pyfolio/pull/242

**Comment by twiecki** [comment]
:+1:
