### ISSUE TITLE
BUG KeyError DatetimeIndex .. are in the [index]", u'occurred at index SMB'

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#249]
A user is reporting that calling create_returns_tear_sheet on current master is causing:

```
/CFD/Programme/CONDA_2/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
/usr/share/themes/Lubuntu-default/gtk-2.0/apps/thunar.rc:55: error: invalid string constant "thunar-statusbar", expected valid string constant
====================================================================================================
Entire data start date: 2002-07-31
Entire data end date: 2015-12-07


Out-of-Sample Months: 132
Backtest Months: 27
                   Backtest  Out_of_Sample  All_History
annual_return          0.12           0.08         0.09
annual_volatility      0.09           0.09         0.09
sharpe_ratio           1.35           0.89         0.96
calmar_ratio           1.27           0.36         0.39
stability              0.89           0.91         0.94
max_drawdown          -0.09          -0.23        -0.23
omega_ratio            1.24           1.18         1.19
sortino_ratio          1.98           1.31         1.41
skewness              -0.16           0.40         0.32
kurtosis               0.49          11.72        10.26
information_ratio     -0.01          -0.00        -0.00
alpha                  0.06           0.05         0.05
beta                   0.38           0.35         0.35
Traceback (most recent call last):
  File "example_permanent.py", line 12, in <module>
    print pf.create_full_tear_sheet(returns, live_start_date='2004-11-29')
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/tears.py", line 160, in create_full_tear_sheet
    set_context=set_context)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/plotting.py", line 46, in call_w_context
    return func(*args, **kwargs)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/tears.py", line 299, in create_returns_tear_sheet
    returns, ax=ax_rolling_risk)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/plotting.py", line 149, in plot_rolling_fama_french
    rolling_window=rolling_window)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/timeseries.py", line 683, in rolling_fama_french
    rolling_window=rolling_window)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/timeseries.py", line 640, in rolling_beta
    rolling_window=rolling_window)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pandas/core/frame.py", line 3914, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pandas/core/frame.py", line 4006, in _apply_standard
    results[i] = func(v)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pandas/core/frame.py", line 3892, in <lambda>
    f = lambda x: func(x, *args, **kwds)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/timeseries.py", line 647, in rolling_beta
    factor_returns.loc[beg:end])[1]
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pyfolio-0.3.1+78.g40cc283.dirty-py2.7.egg/pyfolio/timeseries.py", line 709, in calc_alpha_beta
    beta, alpha = sp.stats.linregress(factor_returns.loc[ret_index].values,
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1198, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1332, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pandas/core/indexing.py", line 942, in _getitem_iterable
    self._has_valid_type(key, axis)
  File "/CFD/Programme/CONDA_2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1280, in _has_valid_type
    (key, self.obj._get_axis_name(axis)))
KeyError: ("None of [DatetimeIndex(['2002-07-31', '2002-08-01', '2002-08-02', '2002-08-05',\n               '2002-08-06', '2002-08-07', '2002-08-08', '2002-08-09',\n               '2002-08-12', '2002-08-13',\n               ...\n               '2003-01-16', '2003-01-17', '2003-01-21', '2003-01-22',\n               '2003-01-23', '2003-01-24', '2003-01-27', '2003-01-28',\n               '2003-01-29', '2003-01-30'],\n              dtype='datetime64[ns, UTC]', name=u'Date', length=127, freq=None)] are in the [index]", u'occurred at index SMB')
```

We're also seeing this on Quantopian research. I can't reproduce the issue locally and there have been several changes to the cache of the Fama-French. I'm running out of ideas of what the issue could be and I can't debug it. Anyone else who can reproduce and debug this further?

**Comment by twiecki** [comment]
CC @ssanderson and @llllllllll who might have an idea.

**Comment by twiecki** [comment]
I figured it out. https://github.com/quantopian/pyfolio/pull/251 should fix it.
