### ISSUE TITLE
Investigate why travis fails on bayesian.py.

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#290]
```
======================================================================
ERROR: test_create_bayesian_tear_sheet_breakdown_0 (pyfolio.tests.test_tears.PositionsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tests/test_tears.py", line 137, in test_create_bayesian_tear_sheet_breakdown
    **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/plotting.py", line 47, in call_w_context
    return func(*args, **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tears.py", line 736, in create_bayesian_tear_sheet
    trace_t, ppc_t = bayesian.run_model('t', df_train,
NameError: global name 'bayesian' is not defined
-------------------- >> begin captured stdout << ---------------------
Running T model
--------------------- >> end captured stdout << ----------------------
======================================================================
ERROR: test_create_bayesian_tear_sheet_breakdown_1 (pyfolio.tests.test_tears.PositionsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tests/test_tears.py", line 137, in test_create_bayesian_tear_sheet_breakdown
    **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/plotting.py", line 47, in call_w_context
    return func(*args, **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tears.py", line 736, in create_bayesian_tear_sheet
    trace_t, ppc_t = bayesian.run_model('t', df_train,
NameError: global name 'bayesian' is not defined
-------------------- >> begin captured stdout << ---------------------
Running T model
--------------------- >> end captured stdout << ----------------------
----------------------------------------------------------------------
Ran 79 tests in 467.312s
FAILED (errors=2)
```

https://travis-ci.org/quantopian/pyfolio/jobs/119783471

**Comment by twiecki** [comment]
Fixed with https://github.com/quantopian/pyfolio/pull/295.
