### ISSUE TITLE
Error running setup.py

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#302]
Running `python setup.py develop` and seeing this:

```
nstalled /private/var/folders/q5/76tqhhm15k9__yjtrbdfhdwm0000gn/T/easy_install-4fYJKk/mock-2.0.0/.eggs/pbr-1.9.1-py2.7.egg
Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/private/var/folders/q5/76tqhhm15k9__yjtrbdfhdwm0000gn/T/easy_install-4fYJKk/mock-2.0.0/.eggs/pbr-1.9.1-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/private/var/folders/q5/76tqhhm15k9__yjtrbdfhdwm0000gn/T/easy_install-4fYJKk/mock-2.0.0/.eggs/pbr-1.9.1-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/private/var/folders/q5/76tqhhm15k9__yjtrbdfhdwm0000gn/T/easy_install-4fYJKk/mock-2.0.0/.eggs/pbr-1.9.1-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 1302, in evaluate_marker
    return cls.interpret(parser.expr(text).totuple(1)[1])
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 1337, in interpret
    return op(nodelist)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 1250, in atom
    return cls.interpret(nodelist[2])
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 1337, in interpret
    return op(nodelist)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py", line 1271, in comparison
    raise SyntaxError(msg)
SyntaxError: '<' operator not allowed in environment markers
error: Setup script exited with error in setup command: Error parsing /private/var/folders/q5/76tqhhm15k9__yjtrbdfhdwm0000gn/T/easy_install-4fYJKk/mock-2.0.0/setup.cfg: SyntaxError: '<' operator not allowed in environment markers

```

**Comment by justinlent** [comment]
realizing this my be a consequence of having upgraded to OSX El Capitan and it breaking a lot of developer related stuff

**Comment by justinlent** [comment]
closing.  El Capitan just totally broke my Anaconda setup. Re-installing Anaconda fixed it
