### ISSUE TITLE
Travis is unhappy

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#505]
```
======================================================================
ERROR: test_create_full_tear_sheet_breakdown_1 (pyfolio.tests.test_tears.PositionsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 142, in wrapped_callable
    func(*args, **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tests/test_tears.py", line 52, in test_create_full_tear_sheet_breakdown
    **kwargs
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tears.py", line 215, in create_full_tear_sheet
    set_context=set_context)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/plotting.py", line 52, in call_w_context
    return func(*args, **kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tears.py", line 566, in create_returns_tear_sheet
    ax=ax_rolling_returns)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/plotting.py", line 857, in plot_rolling_returns
    factor_returns[cum_rets.index], 1.0)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/core/series.py", line 624, in __getitem__
    return self._get_with(key)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/core/series.py", line 667, in _get_with
    return self.reindex(key)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/core/series.py", line 2287, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/core/generic.py", line 2229, in reindex
    fill_value, copy).__finalize__(self)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/core/generic.py", line 2247, in _reindex_axes
    copy=copy, allow_dups=False)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/core/generic.py", line 2341, in _reindex_with_indexers
    copy=copy)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/core/internals.py", line 3586, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/indexes/base.py", line 2293, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```

cc @richafrank.

**Comment by richafrank** [comment]
@twiecki Are we doing anything that changes with each test, like generating and/or using random data? I just ran tests on travis on master, and they passed, and I'm seeing tests passing or failing intermittently on #504 as well...

**Comment by twiecki** [comment]
Did you restart the tests in #504? Very odd, the error message does not make it seem like a stochastic error but I guess it's the only logical conclusion.

**Comment by richafrank** [comment]
Yup, I restarted the tests, and they eventually passed...

**Comment by richafrank** [comment]
The most recent failure on master looks to be from requesting google pricing data. Is it possible that given certain values in the pricing data, we'd see the above errors? From some googling, I see that "This error usually rises when you join / assign to a column when the index has duplicate values."
