### ISSUE TITLE
Travis failure related to beta

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#524]
```
======================================================================
FAIL: test_beta_0 (pyfolio.tests.test_timeseries.TestStats)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose_parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/travis/build/quantopian/pyfolio/pyfolio/tests/test_timeseries.py", line 283, in test_beta
    expected)
AssertionError: -7.228014483236697e-16 != 8.024708101613483e-32
----------------------------------------------------------------------
```

CC @richafrank

**Comment by richafrank** [comment]
Looks like the failure happens on newest empyrical, starting in 0.4.0. cc @llllllllll @ssanderson

**Comment by ssanderson** [comment]
So the thing we appear to be testing here is that the beta of a returns stream against a constant benchmark is 0. If I put a breakpoint in empyrical, the values being passed for the day that's failing this test are:

```
(Pdb++) returns
2000-01-05    0.1
2000-01-06    0.0
2000-01-07    0.0
Freq: D, Name: 0, dtype: float64
(Pdb++) factor_returns
2000-01-05    0.0
2000-01-06    0.0
2000-01-07    0.0
Freq: D, Name: 1, dtype: float64
```

The "mathematically correct" result for this beta calculation is 0, but due to floating point rounding it's unlikely that you'll get exactly 0 from any implementation (you'll only get zero if the sum of a sequence of floats that should add up to zero actually adds up to **exactly** zero, which is unlikely) The test is currently asserting that we emit a beta of exactly `8.024708101613483e-32`, which appears to have been copied from the result that `scipy.stats.linregress` produces. The new vectorized beta fuinction in empyrical uses a different algorithm, and thus produces a different (also very small) value.

I think the right fix for this test is to change the assertion to use `np.assert_almost_equal` or a similar "tolerant equal" check to assert that the beta we get here is zero.

Separately, I see two issues with the current rolling_beta implementation that are probably worth investigating further:

1. The handling of `rolling_window` appears to be off by 1.  The test is calling `rolling_beta` with a window of 2, but stepping through the code we appear to be operating on windows of length 3.
2. `rolling_beta` is implemented by repeatedly calling `empyrical.beta` on hand-computed slices from its input arrays, but `empyrical` already has a `roll_beta` function, which is about 200x faster:

```
In [13]: %timeit pf.rolling_beta(returns, factor, 252)
1 loops, best of 3: 521 ms per loop

In [14]: %timeit ep.stats.roll_beta(returns, factor, 252)
100 loops, best of 3: 2.19 ms per loop
```
