### ISSUE TITLE
conda-forge is broken

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#562]
https://github.com/conda-forge/pyfolio-feedstock/pull/1

Related: https://github.com/quantopian/pyfolio/issues/560

```
/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/test_tmp/run_test.py", line 2, in <module>
    import pyfolio
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/pyfolio/__init__.py", line 3, in <module>
    from . import utils
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/pyfolio/utils.py", line 26, in <module>
    import empyrical.utils
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/empyrical/__init__.py", line 21, in <module>
    from .stats import (
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/empyrical/stats.py", line 23, in <module>
    from .utils import nanmean, nanstd, nanmin, up, down, roll
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/empyrical/utils.py", line 25, in <module>
    from pandas_datareader import data as web
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/pandas_datareader/__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/pandas_datareader/data.py", line 14, in <module>
    from pandas_datareader.fred import FredReader
  File "/home/conda/feedstock_root/build_artifacts/pyfolio_1533248344668/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/pandas_datareader/fred.py", line 1, in <module>
    from pandas.core.common import is_list_like
ImportError: cannot import name 'is_list_like'
Tests failed for pyfolio-0.9.0-py_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for pyfolio-0.9.0-py_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
removing: pyfolio-0.9.0-py_0.tar.bz2
TESTS FAILED: pyfolio-0.9.0-py_0.tar.bz2
Exited with code 1
```

**Comment by twiecki** [comment]
Looks like another pandas incompatibility.
