### ISSUE TITLE
Bayesian tear sheet

### ISSUE THREAD

**Issue by marketneutral** [quantopian/pyfolio#572]
I am having trouble running the Bayesian tear sheet. Theano fails with a "Compilation failed (return status=1)". I can make a minimal repro of the exception as follows (I am filing this here and not in the PyMC3 repo b/c pyfolio requires PyMC3==3.1 which is quite old):

I set up the basic environment which is consistent with pyfolio requirements:
```
conda create -n testenv -y python=3.5 numpy=1.11.3 pandas=0.18.1 scipy=0.17.1 libgfortran=3.0 mkl-service pymc3=3.1 scikit-learn pip
export MKL_THREADING_LAYER=GNU
source activate testenv
```

Following the most basic example of PyMC3 from the docs:

```python
import pymc3 as pm

if __name__=='__main__':
    
    print('Running on PyMC3 v{}'.format(pm.__version__))

    import numpy as np
    import matplotlib.pyplot as plt

    # Initialize random number generator
    np.random.seed(123)

    # True parameter values
    alpha, sigma = 1, 1
    beta = [1, 2.5]

    # Size of dataset
    size = 100

    # Predictor variable
    X1 = np.random.randn(size)
    X2 = np.random.randn(size) * 0.2
    
    # Simulate outcome variable
    Y = alpha + beta[0]*X1 + beta[1]*X2 + np.random.randn(size)*sigma
    
    basic_model = pm.Model()

    with basic_model:

        # Priors for unknown model parameters
        alpha = pm.Normal('alpha', mu=0, sd=10)
        beta = pm.Normal('beta', mu=0, sd=10, shape=2)
        sigma = pm.HalfNormal('sigma', sd=1)
        
        # Expected value of outcome
        mu = alpha + beta[0]*X1 + beta[1]*X2
        
        # Likelihood (sampling distribution) of observations
        Y_obs = pm.Normal('Y_obs', mu=mu, sd=sigma, observed=Y)

    with basic_model:
        # draw 500 posterior samples
        trace = pm.sample(500)

    print(trace['alpha'][-5:])
```
This gives the lengthly exception:

```
Running on PyMC3 v3.1
Auto-assigning NUTS sampler...
Initializing NUTS using ADVI...
Average Loss = 156:   5%|█▎                        | 10316/200000 [00:01<00:20, 9430.53it/s]
Convergence archived at 11100
Interrupted at 11,100 [5%]: Average Loss = 237.04

You can find the C code in this temporary file: /var/folders/sz/_qcyns_12zd21tjhs7q7_29h0000gn/T/theano_compilation_error_y0g4hays
Traceback (most recent call last):
  File "test_pymc3.py", line 44, in <module>
    trace = pm.sample(500)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/pymc3/sampling.py", line 243, in sample
    progressbar=progressbar, **args)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/pymc3/sampling.py", line 604, in init_nuts
    start = approx.sample(draws=njobs)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/pymc3/variational/opvi.py", line 911, in sample
    posterior = self.random_fn(draws)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/pymc3/memoize.py", line 16, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/configparser.py", line 117, in res
    return f(*args, **kwargs)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/pymc3/variational/opvi.py", line 884, in random_fn
    posterior)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/vm.py", line 1091, in make_all
    impl=impl))
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1181, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/anaconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/cmodule.py", line 2388, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', softplus(InplaceDimShuffle{x,0}.0), '\n', "Compilation failed (return status=1): /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:396:27: error: non-constant-expression cannot be narrowed from type 'npy_intp' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing].     int init_totals[2] = {V1_n0, V3_n1};.                           ^~~~~. /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:396:27: note: insert an explicit cast to silence this issue.     int init_totals[2] = {V1_n0, V3_n1};.                           ^~~~~.                           static_cast<int>( ). /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:396:34: error: non-constant-expression cannot be narrowed from type 'npy_intp' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing].     int init_totals[2] = {V1_n0, V3_n1};.                                  ^~~~~. /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:396:34: note: insert an explicit cast to silence this issue.     int init_totals[2] = {V1_n0, V3_n1};.                                  ^~~~~.                                  static_cast<int>( ). /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:408:12: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing].         0, V3_stride1, .            ^~~~~~~~~~. /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:408:12: note: insert an explicit cast to silence this issue.         0, V3_stride1, .            ^~~~~~~~~~.            static_cast<int>( ). /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:409:1: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]. V1_stride0, V1_stride1. ^~~~~~~~~~. /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:409:1: note: insert an explicit cast to silence this issue. V1_stride0, V1_stride1. ^~~~~~~~~~. static_cast<int>( ). /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:409:13: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'int' in initializer list [-Wc++11-narrowing]. V1_stride0, V1_stride1.             ^~~~~~~~~~. /Users/jonathan/.theano/compiledir_Darwin-17.7.0-x86_64-i386-64bit-i386-3.5.6-64/tmp630jrguy/mod.cpp:409:13: note: insert an explicit cast to silence this issue. V1_stride0, V1_stride1.             ^~~~~~~~~~.             static_cast<int>( ). 5 errors generated.. ", '[softplus(<TensorType(float64, row)>)]')
```

I can see that the Travis build for python=3.5, pandas=0.18.1 [is passing](https://travis-ci.org/quantopian/pyfolio/jobs/435667210). That's on ubuntu and I am Mac OS X. Do you have any suggestions on this?

**Comment by marketneutral** [comment]
Solved... this is a Mac OS X issue.

https://stackoverflow.com/questions/51238578/error-non-constant-expression-cannot-be-narrowed-from-type-npy-intp-to-int

```
import theano
theano.config.gcc.cxxflags = "-Wno-c++11-narrowing"
```

And then it all works .... 🙈
